const SITE_URL = "https://organicheritage.store";

const routes = [
  "/",
  "/grains",
  "/cosmetics",
  "/cosmetics/category",
  "/cosmetics/contact",
  "/grains/product/rathasali-rice",
  "/grains/product/thuyamalli-rice",
  "/grains/product/karuppu-kavuni-rice",
  "/grains/product/beetroot-multivitamin-malt",
  "/grains/product/panchamirtha-malt",
  "/grains/product/karuppu-kavuni-idiyappam-flour",
  "/grains/product/rathasali-idiyappam-flour",
  "/grains/product/thuyamalli-idiyappam-flour",
  "/grains/product/thooyamalli-idiyappam-flour",
  "/grains/product/mysore-malli-idiyappam-flour",
  "/grains/product/karuppu-kavuni-puttu-flour",
  "/grains/product/rathasali-puttu-flour",
  "/grains/product/thuyamalli-puttu-flour",
  "/grains/product/mysore-malli-puttu-flour",
  "/grains/product/thuyamalli-kozhukattai-flour",
  "/grains/product/karuppu-kavuni-kozhukattai-flour",
  "/grains/product/rathasali-kozhukattai-flour",
  "/grains/product/mysore-malli-kozhukattai-flour",
  "/grains/product/mappillai-samba-health-mix",
  "/grains/product/mapilai-samba-health-mix",
  "/grains/product/poongar-health-mix",
  "/grains/product/karuppu-kavuni-health-mix",
  "/grains/product/rathasali-health-mix",
  "/grains/product/karuppu-kavuni-soup-mix",
  "/grains/product/rathasali-soup-mix",
  "/grains/product/karuppu-ulunthu-karuppu-kavuni-kali-mix",
  "/grains/product/rathasali-rice-cookies",
  "/grains/product/thuyamalli-rice-cookies",
  "/grains/product/mysore-malli-rice-cookies",
  "/grains/product/multivitamin-cookies",
  "/grains/product/panchamirtha-cookies",
  "/grains/product/karuppu-kavuni-rice-cookies",
  "/grains/product/mysore-malli-murukku-vadam",
  "/grains/product/thanjavur-special-killu-vadam",
  "/grains/product/thanjavur-special-kudaimilagai-vathal",
  "/grains/product/mor-milagai-vathal",
  "/grains/product/kothavarai-vathal",
  "/cosmetics/category/lip-care",
  "/cosmetics/category/skin-care",
  "/cosmetics/category/hair-care",
  "/cosmetics/category/hygiene",
  "/cosmetics/products/natural-lipstick",
  "/cosmetics/products/manjista-lip-balm",
  "/cosmetics/products/strawberry-lip-balm",
  "/cosmetics/products/ghee-infused-lip-butter",
  "/cosmetics/products/beetroot-lip-balm",
  "/cosmetics/products/Herbal-karisalankani-Eye-liner-baby-kajal",
  "/cosmetics/products/face-brightening-night-moisturizer-using-rosehip-seed-oil",
  "/cosmetics/products/saffron-skin-brightening-night-cream",
  "/cosmetics/products/Herbal-karisalankani-Eye-liner-baby-kajal-2",
  "/cosmetics/products/herbal-hair-dye-1",
  "/cosmetics/products/avocado-argan-oil-conditioner",
  "/cosmetics/products/coconut-milk-shampoo",
  "/cosmetics/products/herbal-hair-oil-infused-with-moringa-leaves-and-rosemary-oil",
  "/cosmetics/products/shikkakaai-shampoo-paste",
  "/cosmetics/products/hibiscus-shampoo",
  "/cosmetics/products/herbal-hair-growth-serum",
  "/cosmetics/products/herbal-hair-dye-2",
  "/cosmetics/products/herbal-hair-mask-powder",
  "/cosmetics/products/sanitary-pads-made-with-tapioca-fiber-100-plant-based",
];

export default function sitemap() {
  return routes.map((route) => ({
    url: `${SITE_URL}${route}`,
  }));
}
